### ISSUE TITLE
Use Julia new foreign thread support

### ISSUE THREAD

**Issue by cdsousa** [Clemapfel/jluna#26]
Possibly this is not new news for you, but Julia is about to support foreign threads calling into it: https://github.com/JuliaLang/julia/pull/45447.
This will probably be very helpful and simplify jluna.

**Comment by Clemapfel** [comment]
I was aware of this PR but I'm not sure if I want to bump up the version requirement for Julia to something this new, I'd like it to stay at 1.7. 

If this will be part of the 1.8 stable release then I'll definitely consider reworking the threadpool interface

**Comment by cdsousa** [comment]
This will be only in 1.9.
I agree you don't need to add this as soon as possible, I opened this issue more to raise awareness that such a new feature may be useful for this package in the future. Feel free to close this for now if you prefer 😉

**Comment by Clemapfel** [comment]
Considering the amount of jank I had to implement to get the jluna threadpool to work, it was appropriate to point out - so thank you! Hopefully they also fix `@threadcall` which is currently unusable because of how the C-API work.
