### ISSUE TITLE
jl_set_global going away

### ISSUE THREAD

**Issue by robertu94** [Clemapfel/jluna#34]
Jluna uses a function jl_set_global which seems to be going away in an upcoming version https://docs.julialang.org/en/v1.9-dev/manual/embedding/.  I wasn't sure what the easy work around was otherwise I would have created a PR to adapt to this change.

**Comment by Clemapfel** [comment]
Thank you for making me aware of this, functionality-wise it's pretty easy to replace by just writing a Julia-side function and loading it on `jluna::initialize`, but the nice thing about `jl_set_global` is that it's super fast so I need to do some benchmarking to find a valid replacement.

I'll keep this open until I then, it shouldn't be that much work.

**Comment by Clemapfel** [comment]
Fixed by https://github.com/JuliaLang/julia/commit/3c3ec2e8462bad416a49872daf1401b0745029eb
