### ISSUE TITLE
Build Error on M1 MacBook Pro

### ISSUE THREAD

**Issue by GrantHecht** [Clemapfel/jluna#50]
I'm currently getting build errors (no matching function for call to `box<size_t>(it)` and `unbox<size_t>(it)`) on my M1 MacBook Pro when following the build instructions provided in README.md. 

Here's the CMAKE configuration and make output: 
[buildoutput.txt](https://github.com/Clemapfel/jluna/files/11818182/buildoutput.txt)

**Comment by Clemapfel** [comment]
Sorry for the late reply.

Can you instead compile using GCC or Clang? You are currently using AppleClang, which I have no experience with and no way of testing so I can't even attempt to reproduce this.

You should be able to override the compiler by setting `-DCMAKE_CXX_COMPILER="/usr/bin/g++"` during the `cmake ..` configure step

**Comment by GrantHecht** [comment]
Using GCC 13.1.0, I still get a similar error which seems to be due to the definition of size_t on Mac OS. Here's my cmake and make output using gcc.

[cmake_out.txt](https://github.com/Clemapfel/jluna/files/12001865/cmake_out.txt)
[make_out.txt](https://github.com/Clemapfel/jluna/files/12001867/make_out.txt)
[make_err.txt](https://github.com/Clemapfel/jluna/files/12001866/make_err.txt)

**Comment by GrantHecht** [comment]
Well, I've got jluna building successfully with GCC and AppleClang on my fork [here](https://github.com/GrantHecht/jluna/tree/size_t_error) (just needed to change a few other uses of `size_t` to `uint64_t`).

**Comment by Clemapfel** [comment]
Closed by #52 

Thank you for contributing

**Comment by MorrowChem** [comment]
I get precisely the same error as Grant on my M2 Mac - both on master and size_t_error branches. Can't figure out what's going wrong for me, can build on linux fine.

cmake .. -DCMAKE_CXX_COMPILER=/opt/homebrew/bin/g++-13
make

[make_size_t_error_2.txt](https://github.com/Clemapfel/jluna/files/12701253/make_size_t_error_2.txt)
